---
- name: Prepare build enviroment
  hosts: build
  become: yes

  tasks:

    - name: install packages on build
      apt:
       name:
         - default-jdk
         - maven
         - git
       state: present

    - name: Clone project
      git:
        repo: 'https://github.com/boxfuse/boxfuse-sample-java-war-hello.git'
        dest: /tmp/hello

    - name: build project
      command: mvn package
      args:
        chdir: /tmp/hello


- name: Prepare prod
  hosts: prod
  become: yes

  tasks:

    - name: install packages on prod
      apt:
        name:
          - default-jdk
          - tomcat9
        state: present